### PR TITLE
Add conversion tutorial

### PR DESCRIPTION
**Pull request by cameronmartino**
Open PR for @fedarko

### CODE REVIEW

**Comment by fedarko** [comment]
Things I'd like to address before we merge this in:

- [ ] Mention biplot visualization dependencies in the start of the notebook
- [ ] Prevent the PCs from being called "Differentials" in the Qurro interface (i.e. we need to address #283 first; either that, or export the loadings to a skbio OrdinationResults and use that as Qurro input)
- [ ] Add Qurro screenshot and some brief info about using the visualization to the end of the notebook, similar to the TCGA tutorial's final sections
  - This'll be blocked by the above issue, due to the whole "Differential" thing
- [ ] Merge in my fork, which introduces `read_metadata_file_sane` -- either that or use another method to read in the table/metadata

I think I can take care of these by 3/11.

**Comment by cameronmartino** [comment]
Hi @fedarko, this just had to do with the SVD type being called. This just needed to be switched to a rank 2 partial-SVD, to match the paper. It should match the plot in the paper now (with some possible normal rotational differences).

**Comment by fedarko** [comment]
Thanks @cameronmartino, this is great. I'll add the screenshot stuff in to the end of the notebook, and then once my fork is merged in this should be good.

PS. For posterity—I spent a few minutes trying to understand why paintings `10` and `20` seemed incorrectly placed in the biplot visualization compared to the paper's biplots, since the paper has this consistent 10-1-8 "diagonal"-looking pattern and our visualization has 20 instead of 10 there—and it turns out that there's actually a problem in the Aitchison/Greenacre paper figures! It looks like they wrote `10` instead of `20` in one place, since there are two `10` paintings shown in their figures.

_Paper:_
Screen Shot 2020-03-03 at 5 17 11 PM

_Our notebook:_
image

**Comment by cameronmartino** [comment]
@fedarko, nice catch! Great attention to detail.

**Comment by fedarko** [comment]
@cameronmartino pending your approval, i think this should be good to merge. thanks so much!

**Comment by cameronmartino** [comment]
@fedarko I approve. Thanks!

**Pull request merged**
